env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:import/typescript
  - airbnb
  - airbnb-typescript
  - plugin:react/jsx-runtime
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - plugin:jest/recommended
  - plugin:typescript-sort-keys/recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - '@typescript-eslint'
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-use-before-define:
    - off
  '@typescript-eslint/no-use-before-define':
    - off
  react/no-array-index-key:
    - off
  no-console:
    - error
  react/no-danger:
    - error
  react-hooks/exhaustive-deps:
    - error
  jsx-a11y/click-events-have-key-events:
    - off